/**
 * Generic road scenes for the crash-report guide heroes, keyed by guide slug.
 * Terrain and climate only: no landmarks, seals, flags, badges or agency logos.
 */
export const GUIDE_INDEX_SCENE =
  "a highway interchange where several empty roads cross open countryside under a wide sky, with a single car in the distance";

export const GUIDE_SCENES: Record<string, string> = {
  alabama: "a two-lane highway through tall pine forest, with a single car in the distance",
  alaska: "a mountain highway with snow-capped peaks and spruce trees, with a single car in the distance",
  arizona: "a straight desert highway with tall cacti and red rock mesas far away, with a single car in the distance",
  arkansas: "a winding road through forested rolling hills, with a single car in the distance",
  california: "a coastal highway curving along cliffs above the ocean, with a single car in the distance",
  colorado: "a mountain highway through pine trees below snowy peaks, with a single car in the distance",
  connecticut: "a tree-lined two-lane road with autumn leaves and low stone walls, with a single car in the distance",
  delaware: "a flat coastal highway past green marshland, with a single car in the distance",
  "district-of-columbia": "a city street lined with brick rowhouses and a crosswalk, with a single car in the distance",
  florida: "a highway lined with palm trees near the coast at sunset, with a single car in the distance",
  georgia: "a highway through pine trees with red clay along the roadside, with a single car in the distance",
  hawaii: "a coastal road with tropical plants and green volcanic hills, with a single car in the distance",
  idaho: "a highway along a river canyon beside farmland, with a single car in the distance",
  illinois: "a straight highway through flat cornfields, with a single car in the distance",
  indiana: "a rural road between farm fields with a red barn, with a single car in the distance",
  iowa: "a straight two-lane road through rolling cornfields, with a single car in the distance",
  kansas: "a long straight road across golden wheat fields under a big sky, with a single car in the distance",
  kentucky: "a winding road past wooden horse-farm fences and green hills, with a single car in the distance",
  louisiana: "a highway bridge over bayou wetlands with cypress trees, with a single car in the distance",
  maine: "a coastal road with pine trees beside a rocky shoreline, with a single car in the distance",
  maryland: "a highway along a calm bay shoreline, with a single car in the distance",
  massachusetts: "a town street with brick buildings and autumn trees, with a single car in the distance",
  michigan: "a lakeside highway with birch trees beside a large lake, with a single car in the distance",
  minnesota: "a snowy rural road in winter with evergreen trees, with a single car in the distance",
  mississippi: "a two-lane road through cotton fields and spreading oak trees, with a single car in the distance",
  missouri: "a highway bridge over a wide river with wooded bluffs, with a single car in the distance",
  montana: "an open highway across prairie toward distant mountains, with a single car in the distance",
  nebraska: "a straight road across prairie past grain silos, with a single car in the distance",
  nevada: "a desert highway through sagebrush toward bare mountains, with a single car in the distance",
  "new-hampshire": "a winding mountain road with bright fall foliage, with a single car in the distance",
  "new-jersey": "a busy multi-lane highway passing suburban towns, with a single car in the distance",
  "new-mexico": "a desert highway between mesas and adobe-colored hills, with a single car in the distance",
  "new-york": "a busy city avenue between tall buildings with a crosswalk, with a single car in the distance",
  "north-carolina": "a mountain road along forested ridges at dawn, with a single car in the distance",
  "north-dakota": "a long prairie road past wheat fields and wind turbines, with a single car in the distance",
  ohio: "an interstate highway through farmland and small towns, with a single car in the distance",
  oklahoma: "a highway across red-earth plains with wind turbines, with a single car in the distance",
  oregon: "a highway through tall evergreen forest in light mist, with a single car in the distance",
  pennsylvania: "a highway through rolling forested hills and farmland, with a single car in the distance",
  "rhode-island": "a coastal road beside a small harbor with sailboats, with a single car in the distance",
  "south-carolina": "a highway lined with palmetto trees near marshland, with a single car in the distance",
  "south-dakota": "a highway across grassland toward rocky hills, with a single car in the distance",
  tennessee: "a winding road through green mountains and valleys, with a single car in the distance",
  texas: "a wide highway across open plains under a big sky, with a single car in the distance",
  utah: "a highway through red rock canyon country, with a single car in the distance",
  vermont: "a snowy country road past farmhouses and maple trees, with a single car in the distance",
  virginia: "a two-lane road through rolling hills toward blue mountains, with a single car in the distance",
  washington: "a rainy highway through evergreen forest with mountains far away, with a single car in the distance",
  "west-virginia": "a winding mountain road through dense forest, with a single car in the distance",
  wisconsin: "a rural road past dairy farms and red barns, with a single car in the distance",
  wyoming: "an open highway across high plains toward distant mountains, with a single car in the distance",
};
